apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  annotations:
    app.kubernetes.io/instance: ca-injector
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: ca-injector
    helm.sh/chart: admission-controller-1.0.1
  name: ca-injector
rules:
- apiGroups:
  - ''
  resources:
  - configmaps
  verbs:
  - get
  - read
  - create
