apiVersion: v1
kind: Service
metadata:
  annotations:
    app.kubernetes.io/instance: ca-injector
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: ca-injector
    helm.sh/chart: admission-controller-1.0.1
  name: ca-injector
  namespace: botland
spec:
  ports:
  - name: http
    port: 443
    protocol: TCP
    targetPort: 8443
  selector:
    app: ca-injector
  type: ClusterIP
