apiVersion: v1
kind: Pod
metadata:
  name: nginx
  namespace: default
  annotations:
    "example.com/ca-injector": "true"
  labels:
    name: nginx
spec:
  containers:
  - name: nginx
    image: nginx
