/*
 * Kubernetes Admission Controller
 *
 * This is a generic definition for a Kubernetes Admission Controller
 *
 * API version: 1.0.0
 * Contact: infra@nodis.com.br
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package kac

import (
	"net/http"

	"github.com/gin-gonic/gin"
)

func Health(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{"status": "ok"})
}

// Mutate -
func Mutate(c *gin.Context) {
	serve(c, mutationReviewer)
}

// Validate -
func Validate(c *gin.Context) {
	serve(c, validationReviewer)
}
