/*
 * Kubernetes Admission Controller
 *
 * This is a generic definition for a Kubernetes Admission Controller
 *
 * API version: 1.0.0
 * Contact: infra@nodis.com.br
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package kac

import (
	"context"
	"fmt"
	"io"
	"net/http"

	admissionv1 "k8s.io/api/admission/v1"
	corev1 "k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
	"k8s.io/apimachinery/pkg/runtime/schema"
	"k8s.io/apimachinery/pkg/runtime/serializer"
	"k8s.io/client-go/kubernetes"
	"k8s.io/client-go/kubernetes/fake"
	"k8s.io/client-go/rest"

	"github.com/gin-gonic/gin"
)

const (
	keyFake = "fake"
)

var (
	runtimeScheme = runtime.NewScheme()
	codecFactory  = serializer.NewCodecFactory(runtimeScheme)
	deserializer  = codecFactory.UniversalDeserializer()
)

type AdmissionReviewer func(context.Context, admissionv1.AdmissionReview) (*admissionv1.AdmissionResponse, error)

func init() {
	_ = corev1.AddToScheme(runtimeScheme)
	_ = admissionv1.AddToScheme(runtimeScheme)
}

func errorResponse(c *gin.Context, statusCode int, err error) {
	_ = c.Error(err)
	c.JSON(statusCode, gin.H{"error": err.Error()})
}

func validateAndDeserialize(ar admissionv1.AdmissionReview, expectedGVR metav1.GroupVersionResource, expectedGVK schema.GroupVersionKind) (runtime.Object, error) {
	// Validate resource type
	if ar.Request.Resource != expectedGVR {
		return nil, fmt.Errorf("expect resource to be %s, got %s", expectedGVR, ar.Request.Resource)
	}
	// Deserialize object from AdmissionRequest
	obj, gvk, err := deserializer.Decode(ar.Request.Object.Raw, nil, nil)
	if *gvk != expectedGVK {
		return nil, fmt.Errorf("deserialized object is invalid: %v", obj)
	} else if err != nil {
		return nil, err
	} else {
		return obj, nil
	}
}

func getKubernetesClientSet(ctx context.Context) (kubernetes.Interface, error) {
	if ctx.Value(keyFake) != nil && ctx.Value(keyFake).(bool) {
		c := fake.NewSimpleClientset()
		return c, nil
	} else {
		config, err := rest.InClusterConfig()
		if err != nil {
			return nil, err
		}
		return kubernetes.NewForConfig(config)
	}

}

func serve(c *gin.Context, admissionReviewer AdmissionReviewer) {

	var resp *admissionv1.AdmissionReview
	var body []byte
	var ctx = c.Request.Context()

	if c.Request.Body != nil {
		body, _ = io.ReadAll(c.Request.Body)
	} else {
		errorResponse(c, http.StatusBadRequest, fmt.Errorf("request body is empty"))
		return
	}

	if obj, gvk, err := deserializer.Decode(body, nil, nil); err != nil {
		errorResponse(c, http.StatusBadRequest, err)
		return
	} else {
		req, ok := obj.(*admissionv1.AdmissionReview)
		if !ok {
			errorResponse(c, http.StatusBadRequest, fmt.Errorf("expected v1.AdmissionReview but got: %T", obj))
			return
		}
		resp = &admissionv1.AdmissionReview{}
		resp.SetGroupVersionKind(*gvk)
		resp.Response, err = admissionReviewer(ctx, *req)
		if err != nil {
			errorResponse(c, http.StatusInternalServerError, err)
			return
		}
		resp.Response.UID = req.Request.UID

	}

	c.JSON(http.StatusOK, resp)

}
