/*
 * Kubernetes Admission Controller
 *
 * This is a generic definition for a Kubernetes Admission Controller
 *
 * API version: 1.0.0
 * Contact: infra@nodis.com.br
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package kac

import (
	"net/http"

	"github.com/gin-gonic/gin"
)

// Route is the information for every URI.
type Route struct {
	// Name is the name of this Route.
	Name string
	// Method is the string for the HTTP method. ex) GET, POST etc..
	Method string
	// Pattern is the pattern of the URI.
	Pattern string
	// HandlerFunc is the handler function of this route.
	HandlerFunc gin.HandlerFunc
}

// Routes is the list of the generated Route.
type Routes []Route

// NewRouter returns a new router.
func NewRouter() *gin.Engine {
	gin.SetMode(gin.ReleaseMode)
	router := gin.Default()
	for _, route := range routes {
		switch route.Method {
		case http.MethodGet:
			router.GET(route.Pattern, route.HandlerFunc)
		case http.MethodPost:
			router.POST(route.Pattern, route.HandlerFunc)
		}
	}
	return router
}

var routes = Routes{
	{
		"Health",
		http.MethodGet,
		"/health",
		Health,
	},
	{
		"Mutate",
		http.MethodPost,
		"/mutate",
		Mutate,
	},
	{
		"Validate",
		http.MethodPost,
		"/validate",
		Validate,
	},
}
